### ISSUE TITLE
Support for store (in the flux way)

### ISSUE THREAD

**Issue by stemey** [KnisterPeter/jreact#4]
Hi Markus,

have you put any thoughts into how to support a java backed (flux) store for server rendering? This way the data does not need to be provided as a single initial object but will be pulled by individual components from the stores according to the flux pattern. 

I imagine a Javascript store adapter, that pulls data from a Java store in the same jvm.

**Comment by KnisterPeter** [comment]
It should be no problem at all.
You could create a JReact instance with a pre-setup script engine, where you could add your jvm store object. Then in your react.js code it will be available as global reference.
All you have to do is make sure your frontend and backend store implementations have the same interface.

But besides all that, I think I would prefer to implement the store logic in js and execute it in rhino/nashorn as well. And have a backing implementation which drives the store. This will be a lot simpler I think.

**Comment by stemey** [comment]
So you are suggesting to make an ajax rest call in the server to itself? Is the ajax api actually provided in rhino or nashorn? Are there polyfills for xhr?

**Comment by KnisterPeter** [comment]
No. On the frontend side this will be correct and a backend call is done through xhr.
On the backend side the xhr implementation provided is a stub which does just a message call.
I'm not aware of any polyfills for that, but it is not hard to implement.

But its very application specific to implement flux (since flux is only an architecutre pattern). Therefore it is out of scope for jreact.
Implementing something here is way to complex and generic to be useful.
